
- id: doi:10.48550/arXiv.2504.05585
  group: twcrl
  image: images/project/tw-crl-env.png
  publisher: The 40th Annual AAAI Conference on Artificial Intelligence (AAAI)
  date: '2026-01-20'
  tags:
    - Oral
    - AAAI

- id: doi:10.48550/arXiv.2509.25278
  image: images/project/maestro_motivation_1.png
  publisher: The Thirty-Ninth Annual Conference on Neural Information Processing Systems (NeurIPS)
  date: '2025-12-02'
  tags:
    - Spotlight
    - NeurIPS

- id: doi:10.1145/3772079
  group: homeai_cu
  image: images/project/rasp_teaser.png
  tags:
    - TIOT

- id: doi:10.1145/3737901.3768363
  group: arsteth_cu
  image: images/project/IMUSteth-1.png
  tags:
    - IASA

- id: doi:10.48550/arXiv.2509.05488
  image: images/project/mamba-lite-micro.png
  tags:
    - Preprint

- id: doi:10.1145/3722570.3726888
  group: homeai_cu
  image: images/project/domain_system_architecture_v2-1.png
  tags:
    - Best Paper
    - HumanSys

- id: doi:10.1145/3722570.3726885
  image: images/project/c-pter_t-sne-1.png
  tags:
    - HumanSys

- id: doi:10.1145/3722570.3726887
  image: images/project/dualnet_F1-1.png
  tags:
    - HumanSys

- id: doi:10.1145/3715014.3722081
  group: homeai_cu
  image: images/project/rasp_drone.png
  tags:
    - SenSys

- id: doi:10.48550/arXiv.2502.03682
  image: images/project/ipv_aid_system_flow-1.png
  tags:
    - Preprint

- id: doi:10.1145/3636534.3697460
  image: images/project/tramba_speech_superresolution.png
  tags:
    - MobiCom
    - Poster

- id: doi:10.1145/3636534.3698846
  group: homeai_cu
  image: images/project/rasp_operating_principle.png
  tags:
    - MobiCom
    - Demo

- id: doi:10.48550/arXiv.2411.15281
  image: images/project/elastiformer_figure1-1.png
  tags:
    - Preprint

- id: doi:10.1145/3636534.3697460
  title: 'The Need for Equitable Systems Design: Lessons Learned From A Co-design Study with Low-Income Communities'
  image: images/icon.png
  authors:
    - Stefany Cruz
    - Stephen Xia
    - Maia Jacobs
    - Josiah Hester
  publisher: The First Workshop on Ethical Systems and Architecture Design (HotEthics)
  date: '2024-04-28'
  link: https://hotethics.github.io/papers/Cruz_Hotethics24.pdf
  tags:
    - HotEthics

- id: doi:10.1145/3699757
  image: images/project/tramba_glasses.png
  tags:
    - IMWUT

- id: doi:10.48550/arXiv.2407.05619
  image: images/project/ir_landing_teaser_old-1.png
  tags:
    - Preprint

- id: doi:10.1017/dce.2024.27
  group: energyrec_cu
  image: images/project/RECA_system_architecture.png

- id: doi:10.1145/3600100.3623735
  group: energyrec_cu
  image: images/project/RECA_WebPortal.png
  tags:
    - Best Paper
    - BuildSys
  
- id: doi:10.1145/3570361.3613292
  group: airflow_cu
  image: images/project/teaser_airflow.png
  tags:
    - MobiCom
  
- id: doi:10.1145/3575813.3597350
  group: energyrec_cu
  image: images/project/RLChargers.png
  buttons:
    - type: data
      text: Dataset
      link: https://github.com/Columbia-ICSL/Data-Driven-Human-Centric-EV-Charging
  tags:
    - e-Energy
  
- id: doi:10.1145/3583120.3586962
  group: arsteth_cu
  image: images/project/banner_1_cropped.png
  tags:
    - IPSN
  
- id: doi:10.1145/3576914.3589561
  group: ava_cu
  image: images/project/ExperimentSetup_canrun.png
  tags:
    - IASA
  
- id: doi:10.1145/3576842.3582369
  group: legosense_cu
  image: images/project/hw_overview_v3_cropped.png
  buttons:
    - type: source
      text: Code
      link: https://github.com/Columbia-ICSL/LegoSENSE
  tags:
    - IoTDI
  
- id: doi:10.1109/IPSN54338.2022.00009
  group: fever_cu
  image: images/project/sifter_columbiadoctors.png
  tags:
    - IPSN
  
- id: doi:10.1145/3498361.3538667
  group: legosense_cu
  image: images/project/sensorhub_demo_highlighted.png
  tags:
    - MobiSys
    - Demo
  
- id: doi:10.1145/3498361.3538671
  group: airflow_cu
  image: images/project/Minifly-labelled.png
  tags:
    - MobiSys
    - Demo
  
- id: doi:10.1145/3560905.3568082
  group: arsteth_cu
  image: images/project/guidance2.png
  tags:
    - SenSys
    - Demo
  
- id: doi:10.1145/3560905.3568074
  group: aitherapist_cu
  image: images/project/Experiment_Setup_aitherapist.png
  tags:
    - SenSys
    - Demo
  
- id: doi:10.1109/MPRV.2022.3172419
  group: aitherapist_cu
  image: images/project/answering_naming_frozen-1024x501.png
  
- id: doi:10.1109/IPSN54338.2022.00017
  group: ava_cu
  image: images/project/ava_applications.png
  tags:
    - IPSN
  
- id: doi:10.1145/3539490.3539598
  title: 'BuMA: Non-Intrusive Breathing Detection using Microphone Array'
  group: ava_cu
  image: images/project/1569792226613.jpeg
  tags:
    - IASA
  
- id: doi:10.1145/3539490.3539603
  group: aitherapist_cu
  image: images/project/AI_therapist.png
  tags:
    - IASA
  
  
- id: doi:10.3390/s22041476
  image: images/project/har_sensors-1.png
  
- id: doi:10.1109/DCOSS54816.2022.00029
  group: camnetwork_cu
  image: images/project/0.Implementation-1024x387.png
  tags:
    - DCOSS
  
- id: doi:10.1145/3485730.3492881
  group: homeai_cu
  image: images/project/image-5.png
  buttons:
    - type: demonstration
      text: SenSys 2021 Demo
      link: https://www.youtube.com/watch?v=HxFvBUEluy0
  tags:
    - Best Demo
    - SenSys
    - Demo
  
- id: doi:10.1145/3412382.3458267
  title: 'CSafe: An Intelligent Audio Wearable Platform for Improving Construction Worker Safety in Urban Environments'
  group: urbansafety_cu
  image: images/project/const_site_exp-scaled.jpg
  buttons:
    - type: presentation
      text: IPSN 2021 Presentation
      link: https://www.youtube.com/watch?v=Br3zWFyAwJ0
  tags:
    - IPSN
  
- id: doi:10.1145/3412382.3458784
  group: ava_cu
  image: images/project/source_separation_architecture.png
  tags:
    - IPSN
    - Poster
  
- id: doi:10.1016/j.pmcj.2021.101424
  title: 'SPIDERS+: A light-weight, wireless, and low-cost glasses-based wearable platform for emotion sensing and bio-signal acquisition'
  group: spiders_cu
  image: images/project/spiders_and_manikin.png
  buttons:
    - type: source
      text: Code
      link: https://github.com/Columbia-ICSL/SPIDERS
  
- id: doi:10.1109/IPSN48710.2020.000-1
  group: spiders_cu
  image: images/project/Picture3_spiders.png
  buttons:
    - type: demonstration
      text: IPSN 2020 Demo
      link: https://www.youtube.com/watch?v=SOX7UIqaQGQ
  tags:
    - Best Demo
    - IPSN
    - Demo
  
- id: doi:10.1145/3417313.3429383
  title: 'PAMS: Improving Privacy in Audio-Based Mobile Systems'
  group: ava_cu
  image: images/project/audiospeaker_privacy.PNG
  tags:
    - AIChallengeIoT Workshop
  
- id: doi:10.1109/IoTDI49375.2020.00011
  group: spiders_cu
  image: images/project/Picture7.png
  buttons:
    - type: presentation
      text: IoTDI 2020 Presentation
      link: https://youtu.be/NzPlKYPWuKI
    - type: source
      text: Code
      link: https://github.com/Columbia-ICSL/SPIDERS
  tags:
    - IoTDI
  
- id: doi:10.1109/JIOT.2020.2974848
  group: energyrec_cu
  image: images/project/recEnergyWatch_IoTJ-1024x1024.png
  
- id: doi:10.1109/JIOT.2019.2903519
  group: urbansafety_cu
  image: images/project/Compound_image1_paws.png
  buttons:
    - type: source
      text: Front-End Code
      link: https://github.com/Columbia-ICSL/PAWS-FrontEnd
    - type: source
      text: Android Code
      link: https://github.com/Columbia-ICSL/PAWS-Smartphone

- id: doi:10.1145/3218582
  group: energyfootprint_cu
  image: images/project/energy_apportionment.png
  buttons:
    - type: website
      text: Project Website
      link: http://icsl.ee.columbia.edu/buildingEnergy/
    - type: app
      text: iOS
      link: https://itunes.apple.com/us/app/icsl-energy/id1209898397?mt=8
    - type: app
      text: Android
      link: https://play.google.com/store/apps/details?id=edu.columbia.icsl.androidmobile&hl=en
  tags:
    - TOSN

- id: doi:10.1109/VNC.2018.8628320
  group: urbansafety_cu
  image: images/project/flow_vnc2018.png
  tags:
    - Best Presentation
    - Runner-Up Best App
    - VNC
  
- id: doi:10.3390/s18113775
  group: perspiration_cu
  image: images/project/sweat.png

- id: doi:10.1109/IoTDI.2018.00056
  group: urbansafety_cu
  image: images/project/IMG_20180307_143251.jpg
  tags:
    - Best Demo
    - IoTDI
    - Demo
  
- id: doi:10.1145/3209219.3209244
  group: energyrec_cu
  image: images/project/SketchUp_umap2018.png
  tags:
    - UMAP
  
- id: doi:10.1016/j.smhl.2018.07.012
  group: pillbox_cu
  image: images/project/pillbox-1024x766.jpg
  
- id: doi:10.1145/3267305.3274177
  group: perspiration_cu
  image: images/project/sweat_Simple_Model-1.png
  
- id: doi:10.1109/IoTDI.2018.00031
  group: urbansafety_cu
  image: images/project/Teardown_SEUS.PNG
  buttons:
    - type: source
      text: Front-End Code
      link: https://github.com/Columbia-ICSL/PAWS-FrontEnd
    - type: source
      text: Android Code
      link: https://github.com/Columbia-ICSL/PAWS-Smartphone
  tags:
    - IoTDI
  
- id: doi:10.1016/j.smhl.2018.07.019
  group: legshake_cu
  image: images/project/legshake_plus_personalization.png
  
- id: doi:10.1145/3137133.3137150
  title: 'ePrints: a real-time and scalable system for fair apportionment and tracking of personal energy footprints in commercial buildings'
  group: energyfootprint_cu
  image: images/project/eprint_dashboard.jpg
  buttons:
    - type: website
      text: Project Website
      link: http://icsl.ee.columbia.edu/buildingEnergy/
    - type: app
      text: iOS
      link: https://itunes.apple.com/us/app/icsl-energy/id1209898397?mt=8
    - type: app
      text: Android
      link: https://play.google.com/store/apps/details?id=edu.columbia.icsl.androidmobile&hl=en
  tags:
    - Best Paper Runner-Up
    - BuildSys
  
- id: doi:10.1145/3123024.3124408
  title: 'SPINDLES: A Smartphone Platform for Intelligent Detection and Notification of Leg Shaking'
  group: legshake_cu
  image: images/project/3d_scatter_oppositeleg_highlighted.png
  
- id: doi:10.1145/2994551.2996547
  title: 'SEUS: A Wearable Multi-Channel Acoustic Headset Platform to Improve Pedestrian Safety: Demo Abstract'
  group: urbansafety_cu
  image: images/project/EXP2_CROP_reduced.jpg
  tags:
    - Best Demo Runner-Up
    - SenSys
    - Demo

